apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: ahsimplegorepo 
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: ahsimplegorepo 
    spec:
      containers:
        - name: ahsimplegorepo 
          image: abhisheaAcr.azurecr.io/acrrepo1
          ports:
          - containerPort: 80
